name: Daily Wordle Scraping (Primary + Backup)
on:
  schedule:
    # Updated schedule to run after NYT publishes at 6:00 AM ET
    - cron: '1 10 * * *'   # NYC: 06:01 AM ET - First attempt right after NYT publishes
    - cron: '5 10 * * *'   # NYC: 06:05 AM ET - Quick retry
    - cron: '30 10 * * *'  # NYC: 06:30 AM ET - Third attempt
    - cron: '0 11 * * *'   # NYC: 07:00 AM ET - Fourth attempt
    - cron: '0 12 * * *'   # NYC: 08:00 AM ET - Final backup
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Wordle Scraping
        run: |
          TODAY=$(date +%Y-%m-%d)
          echo "Triggering scrape for date: $TODAY"
          
          # Try direct API call
          RESPONSE=$(curl -s -w "%{http_code}" \
            -H "User-Agent: GitHub-Actions-Primary-Scraper" \
            "https://wordle-answer-today.vercel.app/api/wordle-scrape?date=$TODAY")
          
          HTTP_CODE=${RESPONSE: -3}
          RESPONSE_BODY=${RESPONSE%???}
          
          echo "HTTP Code: $HTTP_CODE"
          echo "Response: $RESPONSE_BODY"
          
          if [ $HTTP_CODE -ge 200 ] && [ $HTTP_CODE -lt 300 ]; then
            echo "✅ Scraping successful"
            # Extract answer if possible for logging
            ANSWER=$(echo "$RESPONSE_BODY" | grep -o '"answer":"[^"]*"' | cut -d'"' -f4 || echo "N/A")
            echo "📝 Answer: $ANSWER"
          else
            echo "❌ Scraping failed with HTTP $HTTP_CODE"
            echo "Response: $RESPONSE_BODY"
            # Don't exit 1 to allow other scheduled jobs to run
          fi