name: Daily Wordle Scraping (Backup)
on:
  schedule:
    # Additional backup schedules when Vercel cron is limited
    - cron: '30 4 * * *'  # NYC: 00:30 EDT
    - cron: '0 7 * * *'   # NYC: 03:00 EDT
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Wordle Scraping
        run: |
          TODAY=$(date +%Y-%m-%d)
          echo "Triggering backup scrape for date: $TODAY"
          
          # Try direct API call
          RESPONSE=$(curl -s -w "%{http_code}" \
            -H "User-Agent: GitHub-Actions-Backup-Scraper" \
            "https://wordle-answer-today.vercel.app/api/wordle-scrape?date=$TODAY")
          
          HTTP_CODE=${RESPONSE: -3}
          RESPONSE_BODY=${RESPONSE%???}
          
          echo "HTTP Code: $HTTP_CODE"
          echo "Response: $RESPONSE_BODY"
          
          if [ $HTTP_CODE -ge 200 ] && [ $HTTP_CODE -lt 300 ]; then
            echo "✅ Backup scraping successful"
          else
            echo "❌ Backup scraping failed with HTTP $HTTP_CODE"
            # Don't exit 1 for backup jobs - let them fail silently
          fi